In [14]:
import re

In [15]:
def tokenize(text):
    tokens = []
    # Expresiones regulares para cada tipo de token
    keywords = re.compile(r'\b(if|else|while)\b')
    identificador = re.compile(r'[a-zA-z][a-zA-Z0-9]*')
    numeros = re.compile(r'\d+')
    operadores = re.compile(r'[\+\-\*\/]')
    delimitador = re.compile(r'[()]|;')
    
    # Extraer palabra por palabra
    for word in text.split():
        if keywords.match(word):
            tokens.append(('KeyWord', word))
        elif identificador.match(word):
            tokens.append(('Identificador', word))
        elif numeros.match(word):
            tokens.append(('Numero', word))
        elif operadores.match(word):
            tokens.append(('Operador', word))
        elif delimitador.match(word):
            tokens.append(('Delimitador', word))
        else:
            tokens.append(('Token Desconocido', word))
    return tokens

In [16]:
# Ejemplo de uso
texto = 'if x > 5 then ( y = t + 1 ) ; else z = z - 1 ;'
tokens = tokenize(texto)
for i in tokens:
    print(i)

('KeyWord', 'if')
('Identificador', 'x')
('Token Desconocido', '>')
('Numero', '5')
('Identificador', 'then')
('Delimitador', '(')
('Identificador', 'y')
('Token Desconocido', '=')
('Identificador', 't')
('Operador', '+')
('Numero', '1')
('Delimitador', ')')
('Delimitador', ';')
('KeyWord', 'else')
('Identificador', 'z')
('Token Desconocido', '=')
('Identificador', 'z')
('Operador', '-')
('Numero', '1')
('Delimitador', ';')

In [17]:
import pandas as pd

In [18]:
tabla = pd.DataFrame(tokens, columns=['Tipo', 'Token'])
tabla

                 Tipo Token
0             KeyWord    if
1       Identificador     x
2   Token Desconocido     >
3              Numero     5
4       Identificador  then
5         Delimitador     (
6       Identificador     y
7   Token Desconocido     =
8       Identificador     t
9            Operador     +
10             Numero     1
11        Delimitador     )
12        Delimitador     ;
13            KeyWord  else
14      Identificador     z
15  Token Desconocido     =
16      Identificador     z
17           Operador     -
18             Numero     1
19        Delimitador     ;

In [19]:
tabla['Tipo'].value_counts()

Tipo
Identificador        6
Delimitador          4
Numero               3
Token Desconocido    3
KeyWord              2
Operador             2
Name: count, dtype: int64

In [20]:
resumen = pd.DataFrame(tabla['Tipo'].value_counts())
resumen['Encontrado'] = ''
resumen

                   count Encontrado
Tipo
Identificador          6
Delimitador            4
Numero                 3
Token Desconocido      3
KeyWord                2
Operador               2

In [21]:
for x, fila in resumen.iterrows():
    listado = tabla[tabla['Tipo'] == x]['Token'].tolist()
    resumen.at[x, 'Encontrado'] = listado
resumen

                   count             Encontrado
Tipo
Identificador          6  [x, then, y, t, z, z]
Delimitador            4           [(, ), ;, ;]
Numero                 3              [5, 1, 1]
Token Desconocido      3              [>, =, =]
KeyWord                2             [if, else]
Operador               2                 [+, -]

In [22]:
# Implementar una funcion que reciba los tokens
def parse(token):
    # Funcion auxiliar para consumir cada token
    def consume(tipo_esperado):
        global token_actual
        if token_actual[0] == tipo_esperado:
            global indice_token
            toekn_actual = tokens[indice_token]
            indice_token += 1
        else:
            raise Exception(f'Se esperaba {tipo_esperado} pero se encontro {token_actual[0]}')
    
    # Reglas de producción como funciones
    def E():
        T()
        F()
        while token_actual[0] in ['+', '-']:
            consume('Operador')
            T()
    
    def T():
        # Implementación de la regla de terminos
        pass
    
    def F():
        # Implementación de la regla de produccion de factores
        pass
    
    # Inicialización de variables
    global token_actual, indice_tokens
    token_actual = tokens[0]
    indice_tokens = 1
    
    # Iniciar el analisis
    E()
    
    # Si se consumieron todos los tokens entonces el analisis fue exitoso
    if indice_tokens == len(tokens):
        return 'Analisis exitoso'
    else:
        raise Exception(f'Error de sintaxis en {token_actual}')